# Run in colab

In [1]:
!pip install instructor

Requirement already satisfied: instructor in /usr/local/lib/python3.12/dist-packages (1.13.0)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from instructor) (3.13.2)
Requirement already satisfied: diskcache>=5.6.3 in /usr/local/lib/python3.12/dist-packages (from instructor) (5.6.3)
Requirement already satisfied: docstring-parser<1.0,>=0.16 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.17.0)
Requirement already satisfied: jinja2<4.0.0,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from instructor) (3.1.6)
Requirement already satisfied: jiter<0.12,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.11.1)
Requirement already satisfied: openai<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.8.1)
Requirement already satisfied: pre-commit>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (4.5.0)
Requirement already satisfied: pydantic-core<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.33.2)
Requirement already satisfied: pydantic<3.0.0,>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.11.10)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from instructor) (2.32.4)
Requirement already satisfied: rich<15.0.0,>=13.7.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (13.9.4)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /usr/local/lib/python3.12/dist-packages (from instructor) (9.1.2)
Requirement already satisfied: ty>=0.0.1a23 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.0.1a27)
Requirement already satisfied: typer<1.0.0,>=0.9.0 in /usr/local/lib/python3.12/dist-packages (from instructor) (0.20.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.9.1->instructor) (1.22.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<4.0.0,>=3.1.4->instructor) (3.0.3)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (0.28.1)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (1.3.1)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.12/dist-packages (from openai<3.0.0,>=2.0.0->instructor) (4.15.0)
Requirement already satisfied: cfgv>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (3.5.0)
Requirement already satisfied: identify>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (2.6.15)
Requirement already satisfied: nodeenv>=0.11.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (1.9.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (6.0.3)
Requirement already satisfied: virtualenv>=20.10.0 in /usr/local/lib/python3.12/dist-packages (from pre-commit>=4.3.0->instructor) (20.35.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.8.0->instructor) (0.7.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.8.0->instructor) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->instructor) (2025.11.12)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=13.7.0->instructor) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich<15.0.0,>=13.7.0->instructor) (2.19.2)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.9.0->instructor) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.9.0->instructor) (1.5.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->openai<3.0.0,>=2.0.0->instructor) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->openai<3.0.0,>=2.0.0->instructor) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.7.0->instructor) (0.1.2)
Requirement already satisfied: distlib<1,>=0.3.7 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor) (0.4.0)
Requirement already satisfied: filelock<4,>=3.12.2 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor) (3.20.0)
Requirement already satisfied: platformdirs<5,>=3.9.1 in /usr/local/lib/python3.12/dist-packages (from virtualenv>=20.10.0->pre-commit>=4.3.0->instructor) (4.5.0)

In [2]:
!cd /content
!rm -rf macro_financial_forecasting

In [3]:
!git clone https://github.com/chuanbinp/macro_financial_forecasting.git

Cloning into 'macro_financial_forecasting'...
remote: Enumerating objects: 1692, done.
remote: Counting objects: 100% (681/681), done.
remote: Compressing objects: 100% (248/248), done.
remote: Total 1692 (delta 510), reused 458 (delta 433), pack-reused 1011 (from 1)
Receiving objects: 100% (1692/1692), 19.11 MiB | 19.99 MiB/s, done.
Resolving deltas: 100% (1041/1041), done.

In [4]:
%cd macro_financial_forecasting/applications/macro_financial_forecasting/src

/content/macro_financial_forecasting/applications/macro_financial_forecasting/src

In [5]:
from config import Config
from train_data_loader import TrainDataLoader
from data_model.bloomberg_news_entry import BloombergNewsEntry
from google.colab import userdata
import os

os.environ["OPENAI_API_KEY"] = userdata.get("OPENAI_API_KEY")
config = Config("../config.env")

train_data_loader = TrainDataLoader(config)

In [6]:
print("Starting loading pipeline ...")
print(f"Config: {config}")

train_ds = train_data_loader.load()
print("Loading pipeline completed.")

Starting loading pipeline ...
Config: Config(
  gemini_api_key: !secret!
  openai_api_key: !secret!
  llm_model: openai/gpt-5-nano-2025-08-07
  industries: ['Information Technology', 'Health Care', 'Financials', 'Consumer Discretionary', 'Communication Services', 'Industrials', 'Consumer Staples', 'Energy', 'Utilities', 'Real Estate', 'Materials', 'General Market', 'None']
  dataset_name: danidanou/Bloomberg_Financial_News
  dataset_dir: ../data/
  rss_feeds: ['https://feeds.bloomberg.com/news/news.rss', 'https://feeds.bloomberg.com/markets/news.rss', 'https://feeds.bloomberg.com/business/news.rss', 'https://feeds.bloomberg.com/technology/news.rss', 'https://feeds.bloomberg.com/politics/news.rss', 'https://feeds.bloomberg.com/wealth/news.rss', 'https://feeds.bloomberg.com/economics/news.rss', 'https://feeds.bloomberg.com/green/news.rss', 'https://feeds.bloomberg.com/pursuits/news.rss', 'https://feeds.bloomberg.com/opinion/news.rss', 'https://feeds.bloomberg.com/finance/news.rss', 'https://feeds.bloomberg.com/real-estate/news.rss', 'https://feeds.bloomberg.com/deals/news.rss', 'https://feeds.bloomberg.com/crypto/news.rss', 'https://feeds.bloomberg.com/europe/news.rss', 'https://feeds.bloomberg.com/uk/news.rss', 'https://feeds.bloomberg.com/asia/news.rss', 'https://feeds.bloomberg.com/commodities/news.rss', 'https://feeds.bloomberg.com/currencies/news.rss', 'https://feeds.bloomberg.com/fixed-income/news.rss', 'https://feeds.bloomberg.com/equities/news.rss', 'https://feeds.bloomberg.com/etfs/news.rss']
  prompt_instructions: You are a financial news analyst.
1. Read the article carefully and classify its **primary industry ... (truncated)
)
Downloading dataset 'danidanou/Bloomberg_Financial_News' with split 'train' from the Hugging Face Hub...

bloomberg_financial_data.parquet.gzip:   0%|          | 0.00/482M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/446762 [00:00<?, ? examples/s]

--- Download Successful! ---

Map:   0%|          | 0/446762 [00:00<?, ? examples/s]

Training dataset processed.

--- Starting validation of 446762 entries ---

Validating entries: 100%|██████████| 446762/446762 [00:27<00:00, 16422.90it/s]

--- Validation Complete! ---
Training dataset validated.
Saving processed dataset to local cache at '../data/danidanou_Bloomberg_Financial_News_train'...
Total number of rows: 446762
Loading pipeline completed.

In [7]:
train_ds[0]

BloombergNewsEntry(Headline='Ivory Coast Keeps Cocoa Export Tax Below 22%, Document Shows', Date='2011-10-06', Link='http://www.bloomberg.com/news/2011-10-06/ivory-coast-keeps-cocoa-export-tax-below-22-document-shows.html', Article='Export taxes on cocoa beans from Ivory Coast , the world’s biggest producer of the chocolate ingredient, won’t exceed 22 percent of the international price this season, meeting a commitment to the International Monetary Fund , according to a finance ministry document. In the 2008-9 season taxes averaged 25.3 percent of international prices, the IMF said in a document posted on its website in November last year. While the country met the commitment in the season just ended, it had a change in government earlier this year. The rate meets a demand by the International Monetary Fund and the World Bank to reform the Ivorian cocoa and coffee industries in order to comply with the terms of its Heavily Indebted Poor Countries’ debt-relief program. Last year, the fixed duty on cocoa beans was scrapped and replaced with a levy that varies with prices as part of the reforms that will make the country eligible for $3 billion in debt relief from the Washington-based lenders. The document from the Abidjan-based ministry is dated Oct. 3 and applies to the 2011-12 harvest season, which began on Oct. 1. It was obtained by Bloomberg and hasn’t been publicly released. Norbert Komenan, an adviser to Finance Minister, Charles Koffi Diby, declined to comment when called today. The main export tax has been maintained at 14.6 percent. There are a number of other charges. Cocoa traded at $2,648 a metric ton in New York as of 11:03 a.m. local time. Disputed Election Discussions of the reform strategy with the World Bank are expected to resume in coming months, the IMF said on its website in July, two months after Alassane Ouattara was sworn in as president following a violent five-month political crisis that was sparked by a disputed November election. Cocoa and coffee exports were largely halted during that time, as Ouattara attempted to limit the flow of funds to Laurent Gbagbo , who refused to cede power despite losing the election. Businesses also shut their doors as customers stayed home and banks closed their branches amid the clashes. As many as 3,000 people were killed, according to the International Criminal Court , which is investigating crimes it says were committed by supporters of both leaders. Ivory Coast’s economy may contract 5.8 percent this year before expanding 8.5 percent in 2012, the ministry said last month. To contact the reporter on this story: Baudelaire Mieu in Abidjan at  bmieu@bloomberg.net  To contact the editor responsible for this story: Antony Sguazzin at  asguazzin@bloomberg.net', Industry=None, KeyPoints=None)

## Update these 2 variables to run pipeline on

In [8]:
DATA_START=0
DATA_END=20

In [9]:
from processor import NewsProcessor
import nest_asyncio
nest_asyncio.apply()

processor = NewsProcessor(config)
results = await processor.transduce_news_entries_async(train_ds[DATA_START:DATA_END], save_path_prefix="processed_news") #Sample 50 news

Processing news:   0%|          | 0/20 [00:00<?, ?entry/s]

AttributeError: 'ProxyClientChat' object has no attribute 'acall'

In [ ]:
processed_df = processor.group_by_date_and_industry(results, save_path="grouped_data")

In [35]:
processed_df

,Industry,Date,News
0,Communication Services,2007-11-02,"[{'Article': 'OAO Comstar United Telesystems, ..."
1,Communication Services,2010-02-05,"[{'Article': 'Tony Hall, the 58-year-old chief..."
2,Communication Services,2010-06-14,"[{'Article': 'Le Monde, France’s newspaper of ..."
3,Communication Services,2011-08-03,"[{'Article': 'Telecom Italia SpA (TIT) , the n..."
4,Communication Services,2011-08-04,"[{'Article': 'Netia SA (NET) , Poland’s second..."
...,...,...,...
667,Utilities,2013-04-30,"[{'Article': 'Iberdrola SA (IBE) , the Spanish..."
668,Utilities,2013-07-10,"[{'Article': 'Cia. Paranaense de Energia , Bra..."
669,Utilities,2013-07-17,[{'Article': 'The U.K.’s longest heat wave in ...
670,Utilities,2013-07-19,"[{'Article': 'Australia ’s New South Wales, th..."
671,Utilities,2013-07-26,[{'Article': 'The World Bank agreed to invest ...

In [36]:
processed_df = await processor.process_dataframe(processed_df, save_path="sentiment_data")

Summarizing: 100%|██████████| 672/672 [06:27<00:00,  1.73it/s]
FinBERT Sentiment: 100%|██████████| 6/6 [00:13<00:00,  2.24s/it]
Explanation: 100%|██████████| 672/672 [02:55<00:00,  3.83it/s]

In [38]:
processed_df

,Industry,Date,News,Summary,SentimentScore,SentimentExplanation
0,General Market,2007-09-07,"[{'Article': 'Russian stocks dropped, led by O...","- U.S. payrolls fell 4,000 in August, first de...",0.011075,The near-zero FinBERT score indicates a neutra...
1,Consumer Discretionary,2007-09-07,"[{'Article': 'Etam Developpement SA (CS) , Fra...","Etam Developpement SA, France's largest public...",0.010423,Near-neutral sentiment (FinBERT ≈ 0.01) driven...
2,Communication Services,2007-11-02,"[{'Article': 'OAO Comstar United Telesystems, ...",- Comstar United Telesystems reported a third-...,0.012233,The FinBERT score of 0.012 indicates a near-ne...
3,Real Estate,2007-12-13,"[{'Article': 'Centro Properties Group , Austra...",Centro Properties Group plans to revise its ea...,0.015082,Explanation: The FinBERT score of 0.015 sugges...
4,Financials,2007-12-13,[{'Article': 'Irish Life & Permanent Plc fell ...,- Irish Life & Permanent warned 2008 operating...,0.010902,FinBERT score of 0.011 indicates near-neutral ...
...,...,...,...,...,...,...
667,Industrials,2013-07-28,[{'Article': '(Corrects Nissan’s reporting dat...,"- GM outsold Toyota in the June quarter, deliv...",-0.005119,FinBERT score -0.005 suggests near-neutral sen...
668,Real Estate,2013-07-29,[{'Article': '(Corrects size of loss in first ...,"- Homex posts a 10.2 billion peso loss, its bi...",0.011860,The FinBERT score of 0.012 implies near-neutra...
669,Industrials,2013-07-29,[{'Article': '(Corrects spelling of hometown i...,Summary\n- Dennis Dammerman died July 23 at 67...,0.523384,The FinBERT score of 0.523 implies a mildly po...
670,Health Care,2013-07-29,"[{'Article': 'Barnaby Jack, the 36-year-old ha...",Barnaby Jack was a computer-security researche...,0.815967,The FinBERT score of 0.816 indicates a positiv...
671,General Market,2013-08-16,[{'Article': 'The Canadian dollar fell for the...,Summary\n- Canadian dollar weakened after June...,0.000396,The article shows a balanced mix of headwinds ...

In [40]:
pd.read_parquet("../data/sentiment_data")

,Industry,Date,News,Summary,SentimentScore,SentimentExplanation
0,General Market,2007-09-07,"[{'Article': 'Russian stocks dropped, led by O...","- U.S. payrolls fell 4,000 in August, first de...",0.011075,The near-zero FinBERT score indicates a neutra...
1,Consumer Discretionary,2007-09-07,"[{'Article': 'Etam Developpement SA (CS) , Fra...","Etam Developpement SA, France's largest public...",0.010423,Near-neutral sentiment (FinBERT ≈ 0.01) driven...
2,Communication Services,2007-11-02,"[{'Article': 'OAO Comstar United Telesystems, ...",- Comstar United Telesystems reported a third-...,0.012233,The FinBERT score of 0.012 indicates a near-ne...
3,Real Estate,2007-12-13,"[{'Article': 'Centro Properties Group , Austra...",Centro Properties Group plans to revise its ea...,0.015082,Explanation: The FinBERT score of 0.015 sugges...
4,Financials,2007-12-13,[{'Article': 'Irish Life & Permanent Plc fell ...,- Irish Life & Permanent warned 2008 operating...,0.010902,FinBERT score of 0.011 indicates near-neutral ...
...,...,...,...,...,...,...
667,Industrials,2013-07-28,[{'Article': '(Corrects Nissan’s reporting dat...,"- GM outsold Toyota in the June quarter, deliv...",-0.005119,FinBERT score -0.005 suggests near-neutral sen...
668,Real Estate,2013-07-29,[{'Article': '(Corrects size of loss in first ...,"- Homex posts a 10.2 billion peso loss, its bi...",0.011860,The FinBERT score of 0.012 implies near-neutra...
669,Industrials,2013-07-29,[{'Article': '(Corrects spelling of hometown i...,Summary\n- Dennis Dammerman died July 23 at 67...,0.523384,The FinBERT score of 0.523 implies a mildly po...
670,Health Care,2013-07-29,"[{'Article': 'Barnaby Jack, the 36-year-old ha...",Barnaby Jack was a computer-security researche...,0.815967,The FinBERT score of 0.816 indicates a positiv...
671,General Market,2013-08-16,[{'Article': 'The Canadian dollar fell for the...,Summary\n- Canadian dollar weakened after June...,0.000396,The article shows a balanced mix of headwinds ...

## JIT Fix

In [39]:
import pandas as pd
from utils.pydantic_parquet_util import ParquetUtil

results = pd.read_parquet("../data/processed_news_batch_1")

In [22]:
df = (
    pd.read_parquet("../data/processed_news_batch_1").groupby(['Industry', 'Date'])
    .apply(lambda x: x.to_dict(orient='records'))
    .reset_index()
    .rename(columns={0: 'News'})
)
ParquetUtil.save_df_to_parquet(df, "../data/grouped_data")

/tmp/ipython-input-1032707156.py:3: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda x: x.to_dict(orient='records'))